[package]
name = "rocket_prometheus"
description = """
Prometheus instrumentation for Rocket applications.
"""
version = "0.7.0"
authors = ["Ben Sully <ben@bsull.io>"]
repository = "https://github.com/sd2k/rocket_prometheus"
edition = "2018"
license = "MIT/Apache-2.0"
keywords = ["rocket", "prometheus", "instrumentation", "monitoring"]
readme = "README.md"

[dependencies]
prometheus = { version = "0.11", default-features = false }
rocket = { rev = "031948c1daaa146128d8a435be116476f2adde00", git = "https://github.com/SergioBenitez/Rocket.git", default-features = false }

[dev-dependencies]
once_cell = "1.2"
rocket_contrib = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[badges]
maintenance = { status = "passively-maintained" }
